# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kinship' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
   pod 'IQKeyboardManagerSwift', '6.3.0'
   pod 'NotificationBannerSwift', '~> 3.0.0'
   pod 'SDWebImage', '~> 5.0'
   pod 'RESegmentedControl'
   pod 'TagListView'
   pod 'AEOTPTextField'
   pod 'CountryPickerView'
   pod 'AlamofireObjectMapper', '~> 5.2'
   pod 'SDWebImage/MapKit'
   pod 'LGSideMenuController'
   pod 'FirebaseMessaging'
   pod 'SVPinView'
   #pod 'URLLivePreview'
   pod 'ActiveLabel'
   pod 'DropDown'
   pod 'FirebaseCore'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
